version: '3.8'

services:
  # Backend Service
  celian-backend:
    restart: 'on-failure'
    build: 
      context: ./driver-cart
    # image: registry.gitlab.com/scm42/banking-system/service-config:latest
    ports:
      - "8082:8080"
    environment:
      - SPRING_APPLICATION_NAME=CELIAN
      - SPRING_CLOUD_CONFIG_SERVER_GIT_URI=https://github.com/scmc24/cloud-conf
      - SPRING_DATASOURCE_URL=jdbc:mysql://celian-db:3306/drivercart
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=
      - SPRING_DATASOURCE_DRIVER-CLASS-NAME=com.mysql.cj.jdbc.Driver
      - SPRING_JPA_HIBERNATE_DDL-AUTO=update
      - SPRING_JPA_SHOW-SQL=true
      - SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL=true
      - SPRING_SQL_INIT_MODE=always
      - SPRING_JPA_DEFER-DATASOURCE-INITIALIZATION=true
      - SERVER_PORT=8080
    depends_on:
      - celian-db

  # MySQL Database Service
  celian-db:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_DATABASE: drivercart
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'

    volumes:
      - celian_data:/var/lib/mysql

  # phpMyAdmin Service
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin-celian
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    ports:
      - "7098:80"
    depends_on:
      - celian-db

  # React Frontend Service
  celian-frontend:
    build:
      context: ./drive-cart # Make sure this is the path to your React app
    ports:
      - "3000:80"  # You can change the 3000 port to whichever one you prefer
    depends_on:
      - celian-backend

volumes:
  celian_data:
